### ISSUE TITLE
Making Parallel Calls with Anthropic

### ISSUE THREAD

**Issue by siddarth-getethos** [anthropics/anthropic-sdk-typescript#104]
We have premium membership of Anthropic. We want to make multiple Parallel Calls with Anthropic at the same time. How can we do the same using Anthropic? What is the maximum number of Parallel Calls one can make with Anthropic at the same time?

**Comment by rattrayalex** [comment]
You can make requests in parallel with this SDK as you would with any over in JavaScript; I recommend reading up on the JS concurrency model and tools like `Promise.all()`. 

The maximum number of parallel calls will depend on your rate limits; please contact Anthropic support for more information.
