### ISSUE TITLE
Streaming: How do I send the request back to the client for streaming?

### ISSUE THREAD

**Issue by NiluK** [anthropics/anthropic-sdk-typescript#112]
Hi, so I've got the anthrophic sdk working for the most part, and it works fine. But I just don't know how to send it back to the client.

For context - it's a next 13 app, with supabase as the db. 

Tried using Vercel's AI library for it, but it works to an extent and then gives up. And also the competition object compounds the responses too cf API

Any chance of getting an actual API example for this 

Thanks

**Comment by rattrayalex** [comment]
> but it works to an extent and then gives up

Can you share more here? What code are you using, and what output do you see?

**Comment by rattrayalex** [comment]
We do expect to ship a `.toReadableStream()` API in the near future, hopefully with a `.fromReadableStream()` that you can use on the client. This is how we'd expect you to be able to use it:

```ts
// app/api/ai/route.ts

export async function GET() {
  const params = {stream: true, …};
  const stream = await client.completions.create(params)
  return new Response(stream.toReadableStream())
}
```

```tsx
// frontend.tsx
import { CompletionStream } from '@anthropic-ai/sdk/streaming'

async function getCompletions({ setText }) {
  const response = await fetch('/api/ai')

  const stream = CompletionStream.fromReadableStream(response.body)  

  stream.on('content', (content) => {
    setText(text => text + content)
  })
  
  // or, if you prefer:
  for await (const chunk of stream) {
    setText(text => text + chunk.completion)
  }
}

export default () => {
  const [text, setText ] = useState('')
  useEffect(() => {
    getCompletions({ setText })
  }, [])
  
  return <p>{text}</p>
}
```

What do you think of an API like this?

**Comment by NiluK** [comment]
> but it works to an extent and then gives up

> Can you share more here? What code are you using, and what output do you see?

Yep, so I am using the vercel ai library with Anthrophic Claude as the provider. 

https://sdk.vercel.ai/docs/guides/providers/anthropic

Pretty Standard:

```ts
import { AnthropicStream, StreamingTextResponse } from 'ai'

export async function POST(req: Request) {
  // Extract the `messages` from the body of the request
  const { messages } = await req.json()
 
  const response = await fetch('https://api.anthropic.com/v1/complete', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': process.env.ANTHROPIC_API_KEY
    },
    body: JSON.stringify({
      prompt: prompt,
      model: 'claude-v1',
      max_tokens_to_sample: 300,
      temperature: 0.9,
      stream: true
    })
  })
 
  // Check for errors
  if (!response.ok) {
    return new Response(await response.text(), {
      status: response.status
    })
  }
 
  // Convert the response into a friendly text-stream
  const stream = AnthropicStream(response)
 
  // Respond with the stream
  return new StreamingTextResponse(stream)
}
```

This works but then it just throws an error. 

`error - TypeError: Cannot read properties of undefined (reading 'slice') 


I did some digging and it turns out that for the ai Library, this is due to them not handling the ping event. 

event: ping
data: {}

So when it hits this line 

```ts
const delta = text.slice(previous.length);
```
    
it throws an error because text is undefined as there is no json.completion

```ts
const text = json.completion,
```
    
  
  I am planning to raise a pr to fix this in the library
  
  
  @rattrayalex Yeah those changes look good, maybe look at React Server Components support too while you're on Client SDK development RFCs

**Comment by rattrayalex** [comment]
For the Vercel ai library, they should actually be able to accept the output of this library, eg:

```ts
const response = await client.completions.create(params)

const stream = new AnthropicStream(response)
```
However, I'm not sure if they've added support for that yet - I can ask them to or put up a PR doing so shortly.

**Comment by rattrayalex** [comment]
I've put up a PR to Vercel's `ai` package: https://github.com/vercel-labs/ai/pull/448 it includes a usage example.

**Comment by rattrayalex** [comment]
I'd be happy to leave this issue open until this library offers a nice full-stack solution built-in. 

In the meantime, another suggestion might be to try just returning the result of the `fetch` call directly from your handler. I'm not certain if it'd work, and on the frontend you'd need to use `.getReader()` and `.read()` which can be a pain. Let me know what you find if you try it.

**Comment by rattrayalex** [comment]
What would you want to see for React Server Components btw?

**Comment by NiluK** [comment]
Hmm, I'm not the best expert on RSCs yet, but I would assume that I'd be able to use the SDK server side and return the component. 

Thanks for your work with @vercel/ai, I think this issue can be considered closed, but you may want to keep it open for now until the SDK changes are fully released. 

In the meantime I'll raise a PR explaining how to integrate it with Vercel for folks.

**Comment by rattrayalex** [comment]
Okay, thanks!
