### ISSUE TITLE
Make anthropic-sdk-typescript work for Node v16

### ISSUE THREAD

**Issue by yagil** [anthropics/anthropic-sdk-typescript#15]
Hi Anthropic team,

Using the current SDK with Node v16.14.2 (happens to be a version I'm stuck with for the time being) results in a cascade of errors.

You can use Node's `https` package directly to make it work for older versions of Node. Here's a notional implementation: https://github.com/yagil/ChatIDE/blob/main/src/anthropic-sdk-simple.ts. Might be beneficial to consider officially supporting older version of Node -- folks don't always control that variable.

Also: you're currently using `import { fetchEventSource } from "@fortaine/fetch-event-source";`  which is a fork of `Azure/fetch-event-source` with a single star on GitHub as of this moment (https://github.com/gfortaine/fetch-event-source). It might be intentional, but also took me by surprise.

**Comment by rattrayalex** [comment]
This is done in v0.5.0!
