### ISSUE TITLE
Add tokens count in TS SDK

### ISSUE THREAD

**Issue by alexeygoncharov** [anthropics/anthropic-sdk-typescript#16]
Do we have this counting system in here? https://colab.research.google.com/drive/1cY_YPaV0KUdveAj_nwy7V8gVEDZh_GDz#scrollTo=XBm0Dz-P-8Fm

**Comment by chitalian** [comment]
+1

**Comment by gtaltatra** [comment]
+1

**Comment by chitalian** [comment]
I dug a bit into this. 

There seem to be a few approaches. 

1. Mirror the python implementation: https://github.com/anthropics/anthropic-sdk-python/blob/main/anthropic/tokenizer.py#L51
However this will require us to get tokenizer to compile to WASM
https://github.com/huggingface/tokenizers/issues/63
https://github.com/huggingface/tokenizers/issues/935

2. We can mirror what is happening here: https://github.com/niieani/gpt-tokenizer/blob/main/src/main.ts#L129-L144
But I think this way is a bit more sketch.

Any other ideas for supporting this that is a bit easier or lower hanging?

**Comment by eek** [comment]
Maybe we can use https://github.com/dqbd/tiktoken since it's a BPE tokenizer as well and works great.

**Comment by niieani** [comment]
Author of gpt-tokenizer here. Just FYI I've rewritten [`gpt-tokenizer`](https://github.com/niieani/gpt-tokenizer) to be a complete TypeScript port of OpenAI's tiktoken (with some extra features sprinkled on top). Would be happy to accept a PR to include support for anthropics models.

**Comment by transitive-bullshit** [comment]
See also https://github.com/transitive-bullshit/compare-tokenizers

**Comment by bobber205** [comment]
This is extremely needed and important to determine cost/usage

**Comment by rattrayalex** [comment]
Good news – we expect have a separate package with this functionality released within a few days!

**Comment by bobber205** [comment]
@rattrayalex  That's awesome! I know it's a big ask but do you mind commenting on this thread when it's available?

**Comment by rattrayalex** [comment]
Of course!

**Comment by rattrayalex** [comment]
This is now released! https://www.npmjs.com/package/@anthropic-ai/tokenizer

**Comment by bobber205** [comment]
@rattrayalex  Does this help with completion token counts? That's the much more expensive one.

**Comment by rattrayalex** [comment]
Yes, you can use this to tokenize the responses as well.

**Comment by bobber205** [comment]
D'oh! Of course! Thanks!
