### ISSUE TITLE
Typo in Anthropic SDK documentation

### ISSUE THREAD

**Issue by a20185** [anthropics/anthropic-sdk-typescript#181]

**Comment by a20185** [comment]
<img width="760" alt="image" src="https://github.com/anthropics/anthropic-sdk-typescript/assets/14831358/ce86b0b6-3902-4e52-a0b1-f6fbc70879a0">

Described as the image above.

When I'm trying to copy the demo code, I found that the `HUMAN_PROMPT` variable was undefined. However refer to the README.md in this repo, I found that the variable should be `Anthropic.HUMAN_PROMPT`.

The problem was found in  https://docs.anthropic.com/claude/reference/client-sdks

**Comment by RobertCraigie** [comment]
Thanks for the report, this has been fixed!
