### ISSUE TITLE
Feature request: Include official helper for building `prompt` from OpenAI `messages[]` source

### ISSUE THREAD

**Issue by flexchar** [anthropics/anthropic-sdk-typescript#212]
Include official helper for building `prompt` from OpenAI `messages[]` source.

I believe there is many who would love this and quite surprised it was not done before. :)

**Comment by rattrayalex** [comment]
Can you share an example snippet of what you'd like to see?

**Comment by flexchar** [comment]
Sure thing Alex.

Here is my version in TS:
```ts
// Build a prompt from the messages
function buildClaudePrompt(
    messages: { content: string; role: 'system' | 'user' | 'assistant' }[],
) {
    let prompt = '';

    // Extract system prompt
    let systemPrompt = '';
    if (messages[0].role === 'system') {
        systemPrompt = messages.shift()!!.content;
        prompt = `${Claude.HUMAN_PROMPT} ${systemPrompt}${Claude.AI_PROMPT} OK.`;
    }

    // Build the prompt from the messages
    for (const message of messages) {
        if (message.role === 'user') {
            prompt += ` ${Claude.HUMAN_PROMPT} ${message.content}`;
        } else {
            prompt += `${Claude.AI_PROMPT} ${message.content}`;
        }
    }

    prompt += `${Claude.AI_PROMPT}`;

    return prompt;
}
```

I also happen to have a PHP implementation for it too
```php
// Build the prompt. We will replicate OpenAI input standard to Anthropic API.
// https://console.anthropic.com/docs/prompt-design
//! Notice how the prompt always begins with "\n\nHuman:" and ends with "\n\nAssistant:"
$finalClaudeInput = collect($messages)
    // Claude doesn't support System role, so we will simulate as the beginning of the conversation.
    ->when($messages[0]['role'] === 'system', function (Collection &$collection) {
        $systemMessage = $collection->shift();
        // Rename the role to user
        $systemMessage['role'] = 'user';

        // Prepend the acknowledge "Assistant" message
        $collection->prepend([
            'role' => 'assistant',
            'content' => 'OK.',
        ]);

        // Prepend the system aka "Human" system message
        $collection->prepend($systemMessage);
    })
    ->add([
        'role' => 'assistant',
        'content' => ' ',
    ])
    ->reduce(function (string $carry, array $message) {
        return $carry .
            sprintf(
                "\n\n%s: %s",
                match ($message['role']) {
                    'user' => 'Human',
                    'assistant' => 'Assistant',
                    default => throw new \Exception(
                        'Invalid role provided: ' . $message['role'],
                    ),
                },
                Str::of($message['content'])
                    ->replace(['\n\n', '\r\n'], "\n")
                    ->toString(),
            );
    }, '');
```

The beauty of having one from you guys would implicitly mean that you choose best performing template. For example, the ambiguous handling of the system message. In some cases (php version) I convert system to user with Claude acknowledging it with "OK". Others have suggested to inject as Claude's first reply. Your own [docs](https://docs.anthropic.com/claude/docs/constructing-a-prompt#system-prompt-optional) suggest either injecting all before or appending the first user message. 

It'd be nice to have an input support OpenAI's messages to allow easily replacing GPT models with Claude (there's definitely good use cases and wins for that). It'd save a lot of mental overhead for us developers dealing with it while making it more attractive for more users to give a Claude a chance. 

Let me know what you think!

**Comment by rattrayalex** [comment]
@x5a thoughts?

**Comment by x5a** [comment]
Hi @flexchar. I appreciate your examples and ideas, as well as the thought you put in sharing them.

Currently, we're not able to offer drop-in compatibility with other foundation model APIs. You are welcome to build and independently release such a helper.

I encourage you to continue watching our public announcements for updates and improvements as we continue to evolve our APIs and SDKs.

Speaking of which, our newest model version, `claude-2.1`, was released today and offers first class support for [system prompts](https://docs.anthropic.com/claude/docs/how-to-use-system-prompts). Because many use cases for Claude are unique, the evaluation of prompt performance will be somewhat specific to your individual needs. We provide some prompt engineering resources on our [docs page](https://docs.anthropic.com/claude/docs), which you may have already seen.

Hopefully this addresses your feedback; I encourage you to continue sharing your ideas with our team.

**Comment by flexchar** [comment]
@x5a Zaa Lee, I hope this message finds you well.

I understand you're a competition company to OpenAI and I have first hand experienced that Claude is suitable for a variety of use-cases where chat flow may not be used as much. 

Nevertheless the completion endpoint enforces structure to include a chat flow with `Human` and `Claude` turns. It still forces us developers to adhere to it. Please do consider making a compatible, easy to swap in SDK/API endpoint. It'd be greatly appreciated.

By the way, amazing work with the documentation. I have greatly benefited from the knowledge resources on prompting.
