### ISSUE TITLE
CompletionResponse type does not contain "model" string

### ISSUE THREAD

**Issue by ravintpillai** [anthropics/anthropic-sdk-typescript#22]
This is an example API response using the Completion method:
`[{"stop": "\n\nHuman:", "model": "claude-v1.3-100k", "log_id": "", "exception": null, "truncated": false, "completion": "", "stop_reason":"stop_sequence"}]`

Notably, the Completion Response type seems to be defined as such:

```
export type CompletionResponse = {
  completion: string;
  stop: string | null;
  stop_reason: "stop_sequence" | "max_tokens";
  truncated: boolean;
  exception: string | null;
  log_id: string;
};
```

Which is missing the "model" parameter, present in the completion. Is this intentional? If not, I'm more than happy to PR this minor fix, assuming it is welcome,

**Comment by rattrayalex** [comment]
This is done in v0.5.0: https://github.com/anthropics/anthropic-sdk-typescript/blob/main/resources/completions.ts#L37
