### ISSUE TITLE
Should we remove cross-fetch?

### ISSUE THREAD

**Issue by implicit-invocation** [anthropics/anthropic-sdk-typescript#23]
I saw that `cross-fetch` was added from this PR (https://github.com/anthropics/anthropic-sdk-typescript/pull/7).  
Polyfilling fetch from inside an npm packet is not considered a good practice anymore for certain reasons.  
In my case, it breaks compatibility on Cloudflare worker (throwing `XMLHttpRequest is not defined` error), just removing the `cross-fetch` import fixed the problem.  

So I suggest that we remove the `cross-fetch` import and dependency, and update the README to instruct users to do the polyfill on their own only when needed.

**Comment by rattrayalex** [comment]
This is done as of v0.5.0.
