### ISSUE TITLE
authentication error with latest version

### ISSUE THREAD

**Issue by to-ivanliang** [anthropics/anthropic-sdk-typescript#240]
Got this authentication_error with 0.11 version, but 0.10.2 version works. Any idea about this?

<img width="1082" alt="Screen Shot 2023-12-20 at 2 34 59 PM" src="https://github.com/anthropics/anthropic-sdk-typescript/assets/115646267/54f024f9-c80b-40cd-a56e-94dd8976c99c">

**Comment by rattrayalex** [comment]
This has been fixed in 0.12.0
