### ISSUE TITLE
Add a dangerouslyAllowBrowser option to allow running in the browser

### ISSUE THREAD

**Issue by jkomoros** [anthropics/anthropic-sdk-typescript#248]
I know that #28 and #219 were both closed as not planned.

In many cases it doesn't make sense to call directly from a browser environment because it could expose the secret API key.

However there are some valid use cases, especially adjacent to open source and tinkerers, where a "BYOKey" pattern makes sense. This happens when for example the project is open source, and the creator cannot and should not pay for API use on behalf of users. The user wouldn't want to give their API key directly to the creator of the service to be passed with a proxy, because who knows what the proxy is doing with that key. In this limited case, it makes sense for the webapp be constructed to store the users' API key in localStorage and only send it directly to Anthropic. This kind of set up allows a lot more tinkering-style apps to be built that cannot handle the marginal costs of completions on behalf of their users.

For example, I have built https://github.com/jkomoros/code-sprouts to support OpenAI, but also want to extend it to support Anthropic too.

Obviously, this is a potential footgun if used insecurely. 

OpenAI has resolved this issue by having a `dangerouslyAllowBrowser` key that must be provided to run in a browser context. Something like that could allow this use case while minimizing potential misuse.

**Comment by rattrayalex** [comment]
Unfortunately Anthropic continues to have no plans to change this. We'll be sure to update the issues here if & when this changes.

**Comment by StudentoTechnologies** [comment]
I also need this dangerouslyAllowBrowser thing. Many developers and customers need it, as can be seen in many forums and discussions. I really can't find logic in Anthropic's decision to reject feature that so many people ask for.

**Comment by NikolayMakhonin** [comment]
My main goals:
1) make my application serverless
2) shift all financial operations for payment of anthropic api to users

Of course, inserting the api key into the browser is not safe, but maybe it is possible to do something like OAuth authorization?

**Comment by x5a** [comment]
@jkomoros + thread, see our latest SDK release now offers CORS/dangerouslyAllowBrowser support. [[changelog](https://github.com/anthropics/anthropic-sdk-typescript/blob/main/CHANGELOG.md#0270-2024-08-21)]

**Comment by simonw** [comment]
Blogged about this here: https://simonwillison.net/2024/Aug/23/anthropic-dangerous-direct-browser-access/

**Comment by rattrayalex** [comment]
Amazing, thank you @simonw! Note btw that using `dangerouslyAllowBrowser: true` in the SDK will automatically add the `anthropic-dangerous-direct-browser-access: true` header for you, e.g.,

```ts
import Anthropic from '@anthropic-ai/sdk';

const client = new Anthropic({
  apiKey: null,
  dangerouslyAllowBrowser: true
});
```

**Comment by EliasPereirah** [comment]
II'm facing the same problem, my open source interface doesn't work for Anthropic due to this error.
https://github.com/EliasPereirah/OrionChat
