### ISSUE TITLE
Publish an OpenAPI schema

### ISSUE THREAD

**Issue by PaulKinlan** [anthropics/anthropic-sdk-typescript#252]
A lot of the files have a note about being generated with OpenAPI.

We'd love to see the OpenAPI spec published. The intent is not to compete with Stainless, but we have a runtime that is unlikely to be supported by other service providers and being able to generate client interfaces to the API at runtime is critical for us. The Open AI OpenAPI (heh, toungue twister) wrapper we have works well and we have some people asking for it with Claude.

**Comment by rattrayalex** [comment]
Thanks Paul, I think this is a great idea and I'll raise it with the team. 

Out of curiosity, what's your runtime, if you can share?

**Comment by rattrayalex** [comment]
Anthropic does plan to do this, but not imminently (and it's not an SDK issue per se) so I'll close this for now.

Thanks for the ask!

**Comment by PaulKinlan** [comment]
@rattrayalex Our runtime is https://github.com/breadboard-ai/breadboard, we do have a custom kit I published (https://github.com/PaulKinlan/claude-breadboard-kit) however we are moving away from custom kits in favour of OpenAPI generated specs directly in the runtime.

re: not an API issue - totally, wasn't sure where else to ask it :D

**Comment by tvanier** [comment]
We would also be interested in the OpenAPI spec, our internal lib is based on OpenAPI-generated code, we use it mostly locally in the browser directly (no node environment) for early evaluations.

**Comment by babogoos** [comment]
Is there any progress about Claude API in OpenAPI schema?
OpenAI has there latest API SPEC publish with [OpenAPI schema](https://github.com/openai/openai-openapi).
It's really helpful that could be test on api testing tools like Postman/Insomnia/Apidog.

**Comment by brainless** [comment]
Hey folks, I understand this is on your radar. One thing I want to add is that with an OpenAPI spec, anyone can generate language bindings. Like I need this for Rust but anyone could need for other languages and the language bindings generator (https://github.com/OpenAPITools/openapi-generator) is quite good.

**Comment by pstutz** [comment]
I was excited to try Claude 3.5 Sonnet for my project, but I noticed that the OpenAPI spec is still not available, and there are only two supported SDKs. Because of this, I've decided to postpone my plans.
