### ISSUE TITLE
Browser support for the SDK

### ISSUE THREAD

**Issue by SuperSonicHub1** [anthropics/anthropic-sdk-typescript#28]

**Comment by rattrayalex** [comment]
You should not call the Anthropic API from the browser, as it would expose your API secret key to the public. 

That said, if you ran into an error with the latest version of the SDK, can you share a traceback of any errors you ran into?

**Comment by SuperSonicHub1** [comment]
> You should not call the Anthropic API from the browser, as it would expose your API secret key to the public.

I want to use the API from the browser for a private dev tool. I can see why this would be an anti-pattern, though. Closing this issue.
