### ISSUE TITLE
Fetch models endpoint

### ISSUE THREAD

**Issue by Retr0-01** [anthropics/anthropic-sdk-typescript#313]
Currently, if any app wants to utilize this SDK they have to hard-code their models and there is no way to dynamically fetch the currently active models provided. This means that in order to update any kind of integration with this SDK we have to manually change the model values provided in our ``message.create()`` options.

This issue is a feature request to create similar endpoints and SDK methods to the [OpenAI API](https://platform.openai.com/docs/models/model-endpoint-compatibility) which provides a way to fetch currently active models across all services.

**Comment by jenan-ant** [comment]
Hello @Retr0-01! We don't have active plans for this, but we're certainly always considering it. We use this repository to track SDK issues, not API features, so I'm going to close this out.
