### ISSUE TITLE
Tool calling example

### ISSUE THREAD

**Issue by josiah-roberts** [anthropics/anthropic-sdk-typescript#316]
We would really benefit from an example of tool calling, ideally with generating tool definitions from [Zod](https://github.com/colinhacks/zod).

If I get this working, I can post my example implementation, but if y'all get to it first that would be super useful.

**Comment by rattrayalex** [comment]
For now, the best reference is this Python repo: https://github.com/anthropics/anthropic-tools

We don't have immediate plans to provide similar helpers in TypeScript, so posting your example implementation would be helpful!

You might consider taking a look [here](https://github.com/openai/openai-node/blob/master/helpers.md#automated-function-calls) and [here](https://github.com/openai/openai-node/blob/master/examples/tool-call-helpers-zod.ts) for inspiration as well.

**Comment by jenan-ant** [comment]
We'll have tools support soon, but in the meantime, please see the above linked repo!

**Comment by joeswann** [comment]
I've been tinkering and think I've got most of a solution in an app I'm whipping up

Check out the formatting functions used in here: [deleted]

Edit: Nevermind I think it hallucinated success, stand by caller.
Edit II: This seems to be working now https://github.com/joeswann/snap/blob/3ebc5e8eab7d6f4b9cadcce74b2a2c2bb0210d6c/src/lib/ai/fetch.ts
