### ISSUE TITLE
More robust chunking

### ISSUE THREAD

**Issue by chitalian** [anthropics/anthropic-sdk-typescript#318]
In some environments, each chunk is not received as a single chunk, but rather the chunk is split up into two chunks.

Right now, the typescript SDK assumes each chunk is formatted as 

```
event: ____
data:  _____
```

However, this is not always the case. Can we add more robust chunking algorithm that waits for all the parts of the chunks?

## Proposed fix

Within `_createMessage` (https://github.com/anthropics/anthropic-sdk-typescript/blob/c7db92c9f6e286c6e344c30fa2b7bc2e0a3ee7f2/src/lib/MessageStream.ts#L123)

We can wait and look for the whole chunk to arrive before adding the next stream event

## Additional notes

The OpenAI Python and Typescript Packages handle this. 

The Ruby OpenAI packages that are community ran, run into this issue: https://github.com/alexrudall/ruby-openai/issues/411

**Comment by RobertCraigie** [comment]
Hey @chitalian can you share an example of something that breaks the SDK streaming logic? The SDK should handle events that come through multiple chunks.

Maybe you ran into #292? (which will be fixed in the next release)

**Comment by rattrayalex** [comment]
This should now be fixed; please try the latest release and provide details if you continue to see issues.
