### ISSUE TITLE
A simple transition guide from OpenAI

### ISSUE THREAD

**Issue by dht** [anthropics/anthropic-sdk-typescript#326]
Is there an easy OpenAI to Claude 3 transition guide?

I am looking to implement in NodeJS Typescript the following capabilities:

- Tools
- AssistantAPI
- Streaming

For tools I am not sure what to make of [this](https://github.com/anthropics/anthropic-tools/).
For the Assistance API I might need to wrap the messages API and manage the state.
The streaming is supported out of the box as I see in [the API docs](https://docs.anthropic.com/claude/reference/messages-streaming).

**Comment by jenan-ant** [comment]
Hello @dht! In the future, this type of request is best answered by the API docs and [support](https://support.anthropic.com/). This repository is used to track issues specific to the TypeScript SDK.

You are correct that we support streaming. See the README.md for this repository, and also our [API docs](https://anthropic.readme.io/claude/reference/messages-streaming).

We'll have more on tools soon, but for now, please refer to the [anthropic-tools](https://github.com/anthropics/anthropic-tools/) repository.

We have no current public plans for an OpenAI-Assistants-like API. Our Messages API is stateless, and closer to OpenAI's Chat Completions.
