### ISSUE TITLE
Essa expressão não pode ser construída.   O tipo 'typeof import("... node_modules/@anthropic-ai/sdk/build/src/index")' não tem assinaturas de constructo.

### ISSUE THREAD

**Issue by lRafaelOliveira** [anthropics/anthropic-sdk-typescript#328]
![image](https://github.com/anthropics/anthropic-sdk-typescript/assets/63177618/fccbbe34-b66e-4829-870e-daea221cdd32)

**Comment by RobertCraigie** [comment]
You shouldn't import from `src`, it's only there for types, if you import from the root package it should work.
