### ISSUE TITLE
Using the API key with Vercel does not work.

### ISSUE THREAD

**Issue by faye1225** [anthropics/anthropic-sdk-typescript#329]
My code is as follows: 
```
import Anthropic from '@anthropic-ai/sdk'
export const runtime = 'edge'

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY || ''
})

export async function POST(req: Request) {

  const message = await anthropic.messages.create({
    max_tokens: 1024,
    messages: [{ role: 'user', content: 'Hello, Claude' }],
    model: 'claude-3-opus-20240229'
  })

  console.log(message.content)

}

```

The version of @anthropic-ai/sdk I am using is 0.17.1.
I can ensure that my key has been correctly imported, and I can get results using Python and Postman.
However, when I use the TypeScript language, I get a 403 {"error":{"type":"forbidden","message":"Request not allowed"}} response.

As shown in the image.

<img width="1146" alt="image" src="https://github.com/anthropics/anthropic-sdk-typescript/assets/56664035/c25c511b-be16-4407-ba76-017d10218ad3">

**Comment by KolvacS-W** [comment]
Hey, I am having the same problem, may I ask how you how you made it work?
