### ISSUE TITLE
[Vertex AI] The constructor does not expose a way to pass custom google credentials

### ISSUE THREAD

**Issue by lbguilherme** [anthropics/anthropic-sdk-typescript#330]
Doing `new AnthropicVertex()` will use the default google credentials. But sometimes this is not what we want to do. Currently we had to use this hack to get it working:

```
const anthropic = new AnthropicVertex({
  region: '...',
  projectId: '...',
});

anthropic._auth = new GoogleAuth({
  scopes: 'https://www.googleapis.com/auth/cloud-platform',
  credentials: JSON.parse(process.env.GOOGLE_CREDENTIALS!),
});
anthropic._authClientPromise = anthropic._auth.getClient();
```

It would be better if an optional `credentials` option could be passed into the `AnthropicVertex` constructor.

**Comment by rattrayalex** [comment]
Thank you for filing, I agree that sounds like a good idea! We'll look into it more soon.

**Comment by RobertCraigie** [comment]
What do you think about supporting an `authConfig?: GoogleAuth` option instead? This way we wouldn't have to add support for each config option individually
```ts
const anthropic = new AnthropicVertex({
  region: '...',
  projectId: '...',
  authConfig: new GoogleAuth({
	  scopes: 'https://www.googleapis.com/auth/cloud-platform',
	  credentials: JSON.parse(process.env.GOOGLE_CREDENTIALS!),
	})
});
```

**Comment by RobertCraigie** [comment]
A `googleAuth` client option will be included in the next release!
