### ISSUE TITLE
Google Apps Script runtime support for @anthropic-ai/bedrock-sdk

### ISSUE THREAD

**Issue by dandv** [anthropics/anthropic-sdk-typescript#334]
I work with @zack-anthropic on the [Claude for Sheets™](https://workspace.google.com/marketplace/app/claude_for_sheets/909417792257) extension. CfSh uses the Google Apps Script runtime, which doesn't support library loading, but can make HTTP(S) calls.

The Anthropic API is directly callable through HTTPS, but the Bedrock library goes through a rather complex process of [signing the request](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-signing.html) and adding headers before submitting it to a URL different from the `https://bedrock-runtime.{region_name}.amazonaws.com` endpoint.

Having GAS support would make using the latest version of the library straightforward, and would avoid a cumbersome and partially manual build process. An example of popular library with GAS support is [lodashgs](https://github.com/oshliaer/lodashgs).

The required support would be limited to text prompts and responses without streaming.

**Comment by rattrayalex** [comment]
Do you know of a way for us to test whether it works in gs without opening a web browser? (e.g., for automated tests & CI). 

What doesn't work about the current library today?

**Comment by dandv** [comment]
[clasp](https://github.com/google/clasp) supports [run](https://github.com/google/clasp/blob/master/docs/run.md)ing functions remotely.

@anthropic-ai/bedrock-sdk works fine locally. The problem is that [Google Apps Script doesn't support loading external JS](https://stackoverflow.com/questions/15548124/how-to-load-javascript-from-external-source-and-execute-it-in-google-apps-script), or [NPM packages](https://stackoverflow.com/questions/49204546/using-an-imported-module-inside-google-app-script).

The lodash folks [created a JS build](https://github.com/oshliaer/lodashgs/issues/1), then likely [shared the library](https://developers.google.com/apps-script/guides/libraries#create_and_share_a_library). The ID of the script mentioned at that developer.google.com page is probably the `1SQ0PlSM...` project key at https://github.com/oshliaer/lodashgs.

**Comment by rattrayalex** [comment]
Ah. I don't think we'd want to be responsible for bundling and publishing a separate package for each build. Is this something you can do?

**Comment by dandv** [comment]
I gave it a shot and documented [my work and the issue I ran into](https://github.com/evanw/esbuild/issues/2780#issuecomment-1998575207): an async iterator that Google Apps Script doesn't support, and `esbuild` can't transpile.

While it would be great is esbuild added support for async iterators, would it be possible in the meantime to either refactor that code, or create a minimalistic Anthropic Bedrock module for GAS that doesn't use streams (or `assert`), and just signs and makes the HTTPS request to the Messages API?

**Comment by rattrayalex** [comment]
I'm very sorry, unfortunately we're only able to support environments with async iterator support. You might be best off forking the repo.
