### ISSUE TITLE
Is this SDK available on deno.land as a module?

### ISSUE THREAD

**Issue by leekuo** [anthropics/anthropic-sdk-typescript#335]
I saw the artifacts for a deno build but couldn't locate it on deno.land.

**Comment by rattrayalex** [comment]
It is not – `esm.sh` should work for you, as should `from 'npm:…'`. Do either of those work for you?

**Comment by leekuo** [comment]
Yes thank you for the tip about `esm.sh`.  For others wondering the same thing, I was able to use `esm.sh` with Deno like this:

```
import Anthropic from 'https://esm.sh/@anthropic-ai/sdk@0.18.0';

const anthropic = new Anthropic({ apiKey: ANTHROPIC_API_KEY });

const msg = await anthropic.messages.create({
  model: 'claude-3-opus-20240229',
  max_tokens: 1024,
  messages: [{ role: 'user', content: 'Hello, Claude' }],
});
console.log(msg);
```
