### ISSUE TITLE
[Request] Allowing fallback to $base_url/messages

### ISSUE THREAD

**Issue by BrandonStudio** [anthropics/anthropic-sdk-typescript#336]
Allowing requests to $base_url/messages when $base_url/v1/messages is not available

**Comment by rattrayalex** [comment]
Can you say more about what you're looking for here and why?

**Comment by BrandonStudio** [comment]
I want to use ts SDK with Cloudflare AI Gateway, whose endpoint is `https://gateway.ai.cloudflare.com/v1/{account_id}/{gateway_name}/anthropic/messages`. When setting `ANTHROPIC_BASE_URL` to `https://gateway.ai.cloudflare.com/v1/{account_id}/{gateway_name}/anthropic`, request will be sent to `https://gateway.ai.cloudflare.com/v1/{account_id}/{gateway_name}/anthropic/v1/messages`, resulting in HTTP 404.

**Comment by rattrayalex** [comment]
Interesting… that makes sense. We'll give this some thought.

**Comment by rattrayalex** [comment]
You can use this workaround, by the way:

```ts
client.messages.create(params, { path: '/messages' })
```
Does that suffice for you?

**Comment by rattrayalex** [comment]
I'm told Cloudflare has fixed this on their end, so `/v1/messages` should work there now! 🎉

**Comment by BrandonStudio** [comment]
Thank you!
