### ISSUE TITLE
CORS issue, how to get around it?

### ISSUE THREAD

**Issue by phusting** [anthropics/anthropic-sdk-typescript#342]
I'm getting the following error when using the libraries.   I don't have this issue with OpenAI, Google or Microsoft AI services.  I'm wondering what I could be missing here?

_taskpane.html:1  Access to fetch at 'https://api.anthropic.com/v1/messages' from origin 'https://ghostwriter-ai.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

**Comment by Vagif12** [comment]
Same issue as well when using localhost:3000 on my React App for testing

**Comment by Vagif12** [comment]
@phusting I got around this in development by initiating the fetch module to have "https://cors-anywhere.herokuapp.com" before it:

 const client = new Anthropic({
    fetch: async (url, init)  => {
      console.log('About to make a request', url, init);
      const response = await fetch(`https://cors-anywhere.herokuapp.com/${url}`, init);
      console.log('Got response', response);
      return response;
    },
    apiKey: "apiKey", // defaults to process.env["ANTHROPIC_API_KEY"]
  });
  
but this is not really a solution that would work in production

**Comment by rattrayalex** [comment]
Anthropic's recommendation here is to build a server-side proxy: https://github.com/anthropics/anthropic-sdk-typescript/issues/219#issuecomment-1830324926

**Comment by x5a** [comment]
@phusting @Vagif12 our latest SDK release now offers CORS support [[changelog](https://github.com/anthropics/anthropic-sdk-typescript/blob/main/CHANGELOG.md#0270-2024-08-21)].
