### ISSUE TITLE
Is there way to specify the response I want to be a JSON schema format?

### ISSUE THREAD

**Issue by Andriy-Kulak** [anthropics/anthropic-sdk-typescript#353]
Hi Team! i understand that I can just prompt api to provide response in JSON and then parse the text response. but I was wondering if there is way to force the sdk to reply with JSON valid schema to ensure I always get the response in the format I expect? if not, is this on the roadmap?

Cheers

**Comment by rattrayalex** [comment]
This is definitely on our minds, but we have no plans to share at this time.
