### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by cagataycali** [anthropics/anthropic-sdk-typescript#355]
Hello Anthropic team, looks like the `https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_node.html` link is broken and used in several places in the codebase

https://github.com/anthropics/anthropic-sdk-typescript/blob/ad92b0d536508954ee8b6c83e82bca30eefeb298/packages/bedrock-sdk/examples/streaming.ts#L9

**Comment by RobertCraigie** [comment]
Thanks for the report! Pushing a commit shortly that changes this link to ttps://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_node.html
