### ISSUE TITLE
Feature request: be able to count input tokens before sending message

### ISSUE THREAD

**Issue by marcolarosa** [anthropics/anthropic-sdk-typescript#360]
HI,

I'm wondering how input token counts are determined? And if possible, could the SDK provide a method.

I'm implementing anthropic in an app where the user has to buy credits to use the service but in order to know whether their message should be sent, i need a semi accurate accounting of how many input tokens their next request will consume. Then, I can check that against the credits they have available and forward / deny request as appropriate.

Looking through the SDK there doesn't seem to be a method to do this. There's https://github.com/anthropics/anthropic-sdk-typescript/pull/94/commits/6060837b0b57db50b1eb529cbd7c54530759ca16 which links to another repo which says in the readme "As of the Claude 3 models, this algorithm is no longer accurate, but can be used as a very rough approximation.".

For my use case I would need to know how rough is rough? Though that repo doesn't look very alive...

I also see that after the table on https://docs.anthropic.com/claude/docs/models-overview#model-comparison there is some info about how inputs map to tokens. Using that I could implement my own rough accounting but as mentioned above, it would be nice for the SDK to have a count method that returns a usage that's about right.

**Comment by blitzbearkevin** [comment]
I've been using the [tokenizer](https://www.npmjs.com/package/@anthropic-ai/tokenizer) for 3.X calls, and the count is not too far off actually. Do you need exact (100%) costs? The approximated value is very close.

For example, here's the values I get for 4096 output tokens (which is the max):

- tokenizer: $0.061215
- actual: $0.06144

This is a difference of $0.000225. It would take 44 of these output responses to add up to just one penny.

**Comment by marcolarosa** [comment]
@blitzbearkevin 

Thanks for the info! To be honest I hadn't yet tried the tokenizer because it seemed odd that that functionality wasn't part of the standard sdk and given that the repo hasn't had any activity for many months, I thought I'd ask the question.

Your report has answered part of my question though: it's a pretty good estimate and certainly good enough for my use case.

But the question to the anthropic folks still remains: can this be a method in the SDK or is that tokenizer library the way to go?

**Comment by rattrayalex** [comment]
> can this be a method in the SDK or is that tokenizer library the way to go?

If that library works for you, please use it!

There are no immediate plans to add this to the SDK.

**Comment by marcolarosa** [comment]
ok - can that commit referenced above be pulled in so that the link is available on this repo? Apologies if i've missed it but I don't see it.

It would also be nice if the comment at the top of the tokenizer repo were less confronting about it not being accurate. Perhaps some words to the effect - "As of the Claude 3 models, this algorithm is no longer accurate, but can be used as a very rough approximation. The error may be up to ...%" (hopefully that's a small number like <5%). That's what caused me to ask this question in the first place ;-)
