### ISSUE TITLE
punycode update?

### ISSUE THREAD

**Issue by urizennnn** [anthropics/anthropic-sdk-typescript#365]
```
  (node:16104) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.                                                                                         (Use `node --trace-deprecation ...` to show where the warning was created) 
  ```
  I get this error when i try to run a lua file after configuring node js to load a js file and run directly in the lua file and after testing it with basic log out it worked but when i decide to use it and run the main thing which is my js application it faile

**Comment by rattrayalex** [comment]
We're working to move from `node-fetch` to `undici`, which will resolve this issue. That fix should come out in the next month or two.

In the short term, you can work around this by overriding the dependency in your package.json, eg:

```json
"overrides": {
  "whatwg-url": "13.0.0"
}
```
