### ISSUE TITLE
Request Blocked by CORS policy

### ISSUE THREAD

**Issue by xtan999** [anthropics/anthropic-sdk-typescript#379]
Following the [example](https://docs.anthropic.com/claude/reference/messages-examples) using typescript and angular. This error shows up. Did not have this problem with OpenAI or Google. See similar [issue](https://www.reddit.com/r/ClaudeAI/comments/1b9pn20/cors_error_in_anthropic_api_while_calling_from/)

`chat:1 Access to fetch at 'https://api.anthropic.com/v1/messages' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by rattrayalex** [comment]
Dup of https://github.com/anthropics/anthropic-sdk-typescript/issues/219

**Comment by x5a** [comment]
@xtan999 our latest SDK release now offers CORS support [[changelog](https://github.com/anthropics/anthropic-sdk-typescript/blob/main/CHANGELOG.md#0270-2024-08-21)].
