### ISSUE TITLE
Vertex SDK: Outdated dependency packaged?

### ISSUE THREAD

**Issue by pazars** [anthropics/anthropic-sdk-typescript#382]
The `anthropic-ai/sdk` that `vertex-sdk` packages for me is 0.14 while the latest one at the moment is 0.20.1.
Tried deleting `node_modules` directory, `npm cache clean --force`, and then reinstall.
The source code in npm and yarn websites shows 0.14 as the dependency.

Am I missing something obvious or is this a bug?

**Comment by rattrayalex** [comment]
Hmm, I'm not sure. @RobertCraigie could you take a look?

**Comment by RobertCraigie** [comment]
Thanks for the report, this is indeed a bug, we'll have a fix out shortly.

**Comment by pazars** [comment]
Seems to be fixed now.

**Comment by olu-an** [comment]
Closing based on the comment from @pazars
