### ISSUE TITLE
`tools` must be declared as Tool type to be accepted in the `beta.tools.messages.create` options

### ISSUE THREAD

**Issue by esponges** [anthropics/anthropic-sdk-typescript#386]
I'm testing the `tools` function calling feature. However I'm facing a type error in the `input_schema.type` key of the `Tool` object.

I get a type error with the following array

```
  const tools = [
    {
      name: 'get_weather',
      description: 'Get the weather in celsius for a given location',
      input_schema: {
        type: 'object',
        properties: {
          location: {
            type: 'string',
            description: 'The location to get the weather for',
          },
          unit: {
            type: 'string',
            enum: ['celsius', 'fahrenheit'],
            description: 'The unit to return the temperature in',
          },
          temperature: {
            type: 'number',
            description: 'The temperature to return',
          },
        },
      },
    },
  ];

  const response = await anthropic.beta.tools.messages.create({
    model: MODEL_NAME,
    max_tokens: 4096,
    tools, // here's the error
    messages: [
      {
        role: 'user',
        content: query,
      },
    ],
  });
```

> No overload matches this call.
  Overload 1 of 3, '(body: MessageCreateParamsNonStreaming, options?: RequestOptions<unknown> | undefined): APIPromise<ToolsBetaMessage>', gave the following error.
    Type '{ name: string; description: string; input_schema: { type: string; properties: { location: { type: string; description: string; }; unit: { type: string; enum: string[]; description: string; }; temperature: { ...; }; }; }; }[]' is not assignable to type 'Tool[]'.
      Type '{ name: string; description: string; input_schema: { type: string; properties: { location: { type: string; description: string; }; unit: { type: string; enum: string[]; description: string; }; temperature: { ...; }; }; }; }' is not assignable to type 'Tool'.
        The types of 'input_schema.type' are incompatible between these types.
          Type 'string' is not assignable to type '"object"'.
  Overload 2 of 3, '(body: MessageCreateParamsStreaming, options?: RequestOptions<unknown> | undefined): APIPromise<Stream<MessageStreamEvent>>', gave the following error.
    Type '{ name: string; description: string; input_schema: { type: string; properties: { location: { type: string; description: string; }; unit: { type: string; enum: string[]; description: string; }; temperature: { ...; }; }; }; }[]' is not assignable to type 'Tool[]'.
  Overload 3 of 3, '(body: MessageCreateParamsBase, options?: RequestOptions<unknown> | undefined): APIPromise<ToolsBetaMessage | Stream<MessageStreamEvent>>', gave the following error.
    Type '{ name: string; description: string; input_schema: { type: string; properties: { location: { type: string; description: string; }; unit: { type: string; enum: string[]; description: string; }; temperature: { ...; }; }; }; }[]' is not assignable to type 'Tool[]'.ts(2769)
messages.d.ts(391, 5): The expected type comes from property 'tools' which is declared here on type 'MessageCreateParamsNonStreaming'
messages.d.ts(391, 5): The expected type comes from property 'tools' which is declared here on type 'MessageCreateParamsStreaming'
messages.d.ts(391, 5): The expected type comes from property 'tools' which is declared here on type 'MessageCreateParamsBase'

The above object is correct, the `Tool.InputSchema` expect's an `object` declaration in the `type` key

```
  export interface InputSchema {
    type: 'object';
    ...
  }
``` 

However, if I add the `Tool` type annotation to `tools` the error goes away:

```
import type { Tool } from '@anthropic-ai/sdk/resources/beta/tools/messages.mjs';

  // no type error here!
  const tools: Tool[] = [
  ...
```

using 

```
"@anthropic-ai/sdk": "^0.20.3",
"typescript": "~5.3"
```

this can be reproduced in this [repo](https://github.com/esponges/anthropic-function-calling/blob/4bf61fc725b1473487396875576b45ae5b497d84/src/function-calling.ts)

**Comment by RobertCraigie** [comment]
this is just the way typescript works unfortunately, there isn't anything we can do here.

it's happening because typescript doesn't infer the type properly so you need to give it an explicit type annotation.
