### ISSUE TITLE
Unable to use in Cloudflare Workers

### ISSUE THREAD

**Issue by huhuhang** [anthropics/anthropic-sdk-typescript#392]
The README says it supports Cloudflare Workers, but in reality, it does not support it.

TypeError: import_sdk.Anthropic is not a constructor

**Comment by rattrayalex** [comment]
How are you importing the package?

**Comment by yjp20** [comment]
Hey @huhuhang, are you still having issues? It's possible that you may need to import the package via:

```ts
const { default: Anthropic } = await import("@anthropic-ai/sdk");
```

**Comment by huhuhang** [comment]
> Hey @huhuhang, are you still having issues? It's possible that you may need to import the package via:
> 
> ```ts
> const { default: Anthropic } = await import("@anthropic-ai/sdk");
> ```

Thank you for your reply, it works. 😄
