### ISSUE TITLE
This expression is not constructable has no construct signatures.ts(2351)

### ISSUE THREAD

**Issue by pytour** [anthropics/anthropic-sdk-typescript#396]
![image](https://github.com/anthropics/anthropic-sdk-typescript/assets/19880083/98d67f47-08dd-4e42-962c-1d3f3e555517)

When i declare Anthropic getting error:
 `This expression is not constructable.   Type 'typeof import(/node_modules/@anthropic-ai/sdk/build/src/index")' has no construct signatures.ts(2351)`

Lib version "^0.4.0"
Running in nestjs 10.3.2

**Comment by rattrayalex** [comment]
It seems you may be importing from the wrong place; make sure you're doing `import Anthropic from '@anthropic-ai/sdk'`, not `from '@anthropic-ai/sdk/build/src'` or anything like that. 

If that doesn't fix it, please share more details and we'll reopen.
