### ISSUE TITLE
`iter is not async iterable` error when trying to use streaming API

### ISSUE THREAD

**Issue by dzhng** [anthropics/anthropic-sdk-typescript#40]
Hello - I'm trying to use the stream API on my node 18 env but it throws the below error.
![image](https://github.com/anthropics/anthropic-sdk-typescript/assets/1329503/6af298c4-095c-4566-85bc-b7c2d86a7916)

To repro - run `ANTHROPIC_KEY="your_key" yarn playground` on the `main` branch of this repo:
https://github.com/dzhng/llm-api

I followed the stream implementation exactly as defined in the readme, and there aren't any type issues, so I don't see anything obviously wrong here.

**Comment by rattrayalex** [comment]
Hi @dzhng, so sorry about this – we've released a fix in https://github.com/anthropics/anthropic-sdk-typescript/releases/tag/v0.5.3
