### ISSUE TITLE
Friendlier error message on wrong region?

### ISSUE THREAD

**Issue by dandv** [anthropics/anthropic-sdk-typescript#402]
Creating a message after initializing the client with the following code will fail with an `ENOTFOUND`:

```
import AnthropicBedrock from '@anthropic-ai/bedrock-sdk';

const client = new AnthropicBedrock({
  awsAccessKey: '...',
  awsSecretKey: '...',
  awsRegion: 'us-west-3',
});
```

Inspecting the error shows `cause: FetchError: request to https://bedrock-runtime.us-west-3.amazonaws.com/model/anthropic.claude-3-sonnet-20240229-v1:0/invoke failed, reason: getaddrinfo ENOTFOUND bedrock-runtime.us-west-3.amazonaws.com`. Might be helpful to more directly indicate that the region was incorrect.

**Comment by rattrayalex** [comment]
Thanks for the suggestion! Unfortunately, I'm not sure this would be possible to do; we'll think about it, but in the meantime, you're welcome to share suggestions.
