### ISSUE TITLE
Fetch shim breaks in vercel edge environment

### ISSUE THREAD

**Issue by dzhng** [anthropics/anthropic-sdk-typescript#41]
When I'm using this SDK in a Vercel edge function, on LOCAL only, the request will refuse to send with the below error.
![image](https://github.com/anthropics/anthropic-sdk-typescript/assets/1329503/3c099cc1-5790-4ab3-89aa-1bf53c6ad5c3)

If I change the function back to nodejs environment, it works. OR, if I deploy the actual edge function (e.g. running on the real edge env, not the local one), it will also work.

IMO it's probably as much a Vercel issue as it is an issue with this SDK, but an easy way to fix is to just let users be able to define their own `fetch` implementation. I see that you already have the property for it in `core.js`, just add it as an option in the constructor.

**Comment by rattrayalex** [comment]
Which version of the library are you using? Can you share a full code sample, along with your vercel config?

**Comment by dzhng** [comment]
Latest version of this lib.

Here's a codesandbox to repro: 
https://codesandbox.io/p/sandbox/serene-sammet-6dd394

Go to `/app/api/route.ts`, and point the browser to the `/api` route to run the code.
![image](https://github.com/anthropics/anthropic-sdk-typescript/assets/1329503/9b55a56c-73e3-4d8a-8ca8-53b048697164)

When runtime is set to `edge`, it fails with the error in the screenshot (this is not the exact same error I got, but I think it's because I'm using WSL whereas codesandbox runs another linux distro).

If you change the runtime to `nodejs`, it will be successful (it does throw a bunch of module not found errors, but I think that's just codesandbox issues).

One weird thing is - if I run another simpler prompt (like the one I commented out), it will still work in the `edge` environment. This has me wondering if it's a text encoding issue here.

**Comment by dzhng** [comment]
I think @jaredpalmer is looking into adding Anthropic support to Vercel edge streaming as part of their AI push. I wonder if they ran into similar issues.

**Comment by dzhng** [comment]
OK, it IS an encoding issue, specifically, with the em dash character (although I suspect it basically applies to all multi-byte UTF-8 encoded characters).

For example, even if I just send the em dash char (not normal dash e.g. `-`, but em dash e.g. `—`), it'll break the SDK.

![image](https://github.com/anthropics/anthropic-sdk-typescript/assets/1329503/dc31724d-665e-4cf8-ad9e-d6bccd6a3d5c)

**Comment by dzhng** [comment]
Last update - overriding the `Content-Length` in the header by passing in the correct one that takes into account multi-byte characters works.

![image](https://github.com/anthropics/anthropic-sdk-typescript/assets/1329503/fcdcaa49-9200-4e13-8fe0-b85e8e17d38c)

Wrong length calculation on this line:
https://github.com/anthropics/anthropic-sdk-typescript/blob/main/src/core.ts#L132

The reason why it fails on `edge` is because Vercel uses `undici` in their edge runtime, which defaults to strict re `Content-Length` on write:
https://github.com/nodejs/undici/blob/22bdbd8c7820035276b4e876daccef513c29f5c4/lib/client.js#L1359

**Comment by rattrayalex** [comment]
Thank you so much for the repro and the terrific debugging here, @dzhng ! We'll aim to get a fix out for this today.

It may be a little complicated since `Buffer` isn't available in all runtimes, and we'll want to make sure that our fix is accurate everywhere.

**Comment by jedwards1211** [comment]
I *think* in the non-node case using Web API `fetch` it can set the `Content-Length` header automatically?  But should check

**Comment by jedwards1211** [comment]
Yes from the `fetch` spec it looks like it automatically adds `Content-Length`: https://fetch.spec.whatwg.org/#http-network-or-cache-fetch, steps 8.5-9

**Comment by RobertCraigie** [comment]
This should be fixed in `v0.5.4` - implementation in #47.

Please try it out and let us know if your issue is resolved!
