### ISSUE TITLE
CORS: Message API return CORS issues. 

### ISSUE THREAD

**Issue by firllyw** [anthropics/anthropic-sdk-typescript#410]
<img width="452" alt="image" src="https://github.com/anthropics/anthropic-sdk-typescript/assets/14936524/75c8abc1-798f-4e02-b3c9-6a31c74e9fd4">

Step to Reproduce: 

`const anthropic = new Anthropic({
    apiKey: process.env.NEXT_PUBLIC_ANTHROPIC_API_KEY,
});

function MyDiagrams() {
    const [loading, setLoading] = useState(false);

    const askClaude = async (question) => {
        setLoading(true);
        
        const msg = await anthropic.messages.create({
            model: "claude-3-opus-20240229",
            max_tokens: 4000,
            temperature: 0,
            system: "some prompt engineering here",
            messages: [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": question
                        }
                    ]
                }
            ]
        })

        if (!msg) {
            toast.error('Failed to get response from Claude');
            setLoading(false);
            return;
        }

        setLoading(false);
    }
    
    export default MyDiagrams;
    `
    
    snippet above is from a Page.js . 
    
    Live app: https://flowy-ai.netlify.app/dashboard/my-diagrams/create

**Comment by BrandonStudio** [comment]
Before sending POST request, broswer will first send an OPTIONS preflight request to API (e.g. `https://api.anthropic.com/v1/messages`). But right now Anthropic API endpoint does not allow OPTIONS method.

**Comment by aaronvg** [comment]
Also running into this issue. Anthropic APIs are not callable from the client-side without a proxy server

**Comment by cwray-sdc** [comment]
Also seeing this issue when calling from localhost.

**Comment by rattrayalex** [comment]
Dup of https://github.com/anthropics/anthropic-sdk-typescript/issues/219

**Comment by x5a** [comment]
@firllyw + thread: our latest SDK release now offers CORS support [[changelog](https://github.com/anthropics/anthropic-sdk-typescript/blob/main/CHANGELOG.md#0270-2024-08-21)].

**Comment by EliasPereirah** [comment]
Any updates on this? I'm creating an interface but it doesn't work for **Anthropic**  due to this error.
https://github.com/EliasPereirah/OrionChat/
