### ISSUE TITLE
Incorrect usage.output_tokens value

### ISSUE THREAD

**Issue by dannymyers** [anthropics/anthropic-sdk-typescript#424]
The SDK does not report the correct value for `output_tokens` when using `messages.stream`. It appears to grab the output_tokens from the `message_start` event, but does not update it when it receives the `message_delta` event.

**Comment by RobertCraigie** [comment]
hey @dannymyers are you using the latest version? I believe this bug has been fixed, could you update to the latest version and let me know if that now works for you?

**Comment by dannymyers** [comment]
Awesome - you're right this is fixed in a newer version. Thanks!
