### ISSUE TITLE
Cancellation of requests via AbortSignal

### ISSUE THREAD

**Issue by dqbd** [anthropics/anthropic-sdk-typescript#43]
Previous versions of Anthropic SDK pre 0.5.0 had the option to specify `signal` attribute to prematurely cancel the request, which is now currently taken by the timeout mechanism.

**Comment by rattrayalex** [comment]
You should now be able to accomplish this like so: 

```ts
const stream = client.completions.create({...params, stream: true});

stream.controller.on('abort', myCallback); // listen for cancelation

setTimeout(() => {
  stream.controller.abort(); // can cancel the stream this way.
}, 1000)

for await (const part of stream) {
  if (shouldCancel()) break; // can also cancel the stream this way.
}
```

Does this work for you? Feedback welcome!

**Comment by jacoblee93** [comment]
This works for streaming, but adds a bit of complexity as we'd have to basically add a custom callback on our passed in `signal` and then call `stream.controller.abort()` within that to have the same interface. We'd also love to support aborts for non-streaming requests as well for consistency.

Any way we could allow a custom signal to be passed through as before?

Here's how the current implementation looks: https://github.com/hwchase17/langchainjs/blob/main/langchain/src/chat_models/anthropic.ts#L275

**Comment by rattrayalex** [comment]
Ahh, sorry, I'd missed that. We'll look into this, thank you for raising & clarifying!

**Comment by rattrayalex** [comment]
What is the purpose of the `signal` and its abort in your library? (I didn't see it used in that file; I might be able to explore your source sometime later). 

Partly I'm wondering if the timeouts & retries offered natively by this SDK might serve your needs, but generally I'd like to understand the context a little better so we can provide a great interface.

**Comment by jacoblee93** [comment]
Sure, here's how it looks end-to-end in our docs:

https://js.langchain.com/docs/modules/models/chat/additional_functionality#cancelling-requests

It's not the same thing as a timeout or a retry - one example is someone building a chat interface who wants to have a way to stop an outgoing generation. Not quite as important for non-streaming requests but would still be nice to have it there for consistency's sake.

**Comment by rattrayalex** [comment]
Thank you, makes a ton of sense. We plan to add this shortly like so:

```ts
const completion = await client.completions.create(params, { signal: controller.signal });
```

This would likely raise an `APIAbortError` or `APIUserAbortError` or similar. Feedback/suggestions on this interface welcome!
