### ISSUE TITLE
Please migrate @aws-sdk/signature-v4 and @aws-sdk/protocol-http in the Bedrock SDK

### ISSUE THREAD

**Issue by antstanley** [anthropics/anthropic-sdk-typescript#441]
The modules `@aws-sdk/protocol-http` and `@aws-sdk/signature-v4` have been moved to `@smithy/signature-v4` and `@smithy/protocol-http`.

The packages in the `@aws-sdk` namespace have been marked as deprecated and haven't been updated in a year by AWS, whereas the packages in the `@smithy` namespace are currently maintained, with regular updates.

Updates:
`@aws-sdk/protocol-http` - [https://www.npmjs.com/package/@aws-sdk/protocol-http?activeTab=versions](https://www.npmjs.com/package/@aws-sdk/protocol-http?activeTab=versions)
`@smithy/protocol-http` - [https://www.npmjs.com/package/@smithy/protocol-http?activeTab=versions](https://www.npmjs.com/package/@smithy/protocol-http?activeTab=versions)

`@aws-sdk/signature-v4` - [https://www.npmjs.com/package/@aws-sdk/signature-v4?activeTab=versions](https://www.npmjs.com/package/@aws-sdk/signature-v4?activeTab=versions)
`@smithy/signature-v4` - [https://www.npmjs.com/package/@smithy/signature-v4?activeTab=versions](https://www.npmjs.com/package/@smithy/signature-v4?activeTab=versions)

I was going to submit a PR to resolve this, but I saw that the code base is mainly generated, so wasn't sure where the appropriate place was to fix this.

**Comment by dgellow** [comment]
Thanks @antstanley for reporting this. Assuming you have more context, do I understand correctly the two packages are compatible?

If you still want to submit a PR in this repo, we would appreciate and would reapply the patch on our side to update the SDK

**Comment by rattrayalex** [comment]
it looks like this was fixed in https://github.com/anthropics/anthropic-sdk-typescript/pull/447
