### ISSUE TITLE
typescript has signatures, but none of those signatures are compatible with each other.

### ISSUE THREAD

**Issue by FlowerWrong** [anthropics/anthropic-sdk-typescript#443]
Hi! I am using this sdk in production. When I upgraded to a version later than `0.20.6`, I got this error `has signatures, but none of those signatures are compatible with each other.`. Can you help me?

<img width="880" alt="截屏2024-06-24 09 42 45" src="https://github.com/anthropics/anthropic-sdk-typescript/assets/5362640/984e6d7d-55a4-471d-b336-a1f111d4eb48">

```
await anthropicClient.messages
            .create(
              {
                stream: true,
                messages: sentMessages,
                model: reqModel,
                max_tokens: 1024,
                top_p: otherParams?.top_p,
                top_k: otherParams?.top_k,
                system: otherParams?.system,
              } as any,
              reqConfig,
            )
```

**Comment by rattrayalex** [comment]
Can you share more of your surrounding code? for example, what is `reqConfig`?

**Comment by FlowerWrong** [comment]
> Can you share more of your surrounding code? for example, what is `reqConfig`?

This error has nothing to do with him.
