### ISSUE TITLE
API calls missing Rate Limit Response Headers

### ISSUE THREAD

**Issue by johnmangan** [anthropics/anthropic-sdk-typescript#450]
The documentation on Rate Limits suggests we can see current usage and limits per API request by reading a set of Response Headers. https://docs.anthropic.com/en/api/rate-limits#response-headers

This repository's README tells us how to read Response Headers. https://github.com/anthropics/anthropic-sdk-typescript?tab=readme-ov-file#accessing-raw-response-data-eg-headers

I have tried to make trivial calls, the same as shown in the Response Headers example, with both `asResponse` and `withResponse`. Both return the generated message, but neither is including the Rate Limit headers. The only headers either is returning are:
```
 [
  'cf-cache-status',
  'cf-ray',
  'connection',
  'content-encoding',
  'content-type',
  'date',
  'request-id',
  'server',
  'transfer-encoding',
  'via',
  'x-cloud-trace-context'
]
```

I have also tried this with both a Haiku model and an Opus model, neither returning the rate limit headers.

**Comment by rattrayalex** [comment]
Just to clarify, this is happening in the API, correct? (ie., you see the same behavior with `curl`?) I would not expect the SDKs to be removing these headers.

**Comment by olu-an** [comment]
I've encountered a similar report. Taking a look.

**Comment by johnmangan** [comment]
This has been solved in my individual use-case, through the website support chat. The resolution, in my case, was related to values on my account:

> it looks like your RPM, TPM, and TPD for Opus and Haiku needed to be refreshed as these values weren't properly reflected in our system. This is why you weren't seeing the values for the rate limit headers with your response.

Cheers
