### ISSUE TITLE
Model List?

### ISSUE THREAD

**Issue by aldozorzi** [anthropics/anthropic-sdk-typescript#458]
Hello there, I can't find a method to retrieve models list... I can't believe Anthropic is the only LLM API which doesn't have, so I must missing something... Could anyone help me, please?

**Comment by dandv** [comment]
Anthropic doesn't have an API for that. Web UIs like big-agi [hardcode the list of models](https://github.com/enricoros/big-AGI/blob/main/src/modules/llms/server/anthropic/anthropic.router.ts#L14).

Bedrock does. Here's some Python code to get the list of models via Bedrock, but note the identifiers will be in a different format, e.g. `anthropic.claude-3-haiku-20240307-v1:0`.

```py
import boto3

bedrock = boto3.client(service_name="bedrock", region_name="us-west-2")
response = bedrock.list_foundation_models(byProvider="anthropic")

for summary in response["modelSummaries"]:
    print(summary["modelId"])
```

**Comment by rattrayalex** [comment]
Sorry, Anthropic does not offer an API for listing available models at this time.

**Comment by dandv** [comment]
For those who land here from a search, Anthropic now offers a model list endpoint - https://docs.anthropic.com/en/api/models-list
