### ISSUE TITLE
How to import the Vertex SDK into Cloudflare Workers?

### ISSUE THREAD

**Issue by abs612** [anthropics/anthropic-sdk-typescript#460]
![image](https://github.com/anthropics/anthropic-sdk-typescript/assets/144533817/a2f6f178-f0ac-4f3f-9cd0-f88f52b6ffa4)

```
const { AnthropicVertex } = await import("@anthropic-ai/vertex-sdk");
// or
import { AnthropicVertex } from '@anthropic-ai/vertex-sdk';
```
Both methods result in an error.
```
// ......
 [ERROR] Could not resolve "stream"

    node_modules/jws/lib/data-stream.js:3:21:
      3 │ var Stream = require('stream');
        ╵                      ~~~~~~~~

  The package "stream" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file and make sure to prefix the module name with "node:" to enable Node.js compatibility.


X [ERROR] Could not resolve "util"

    node_modules/jws/lib/data-stream.js:4:19:
      4 │ var util = require('util');
        ╵                    ~~~~~~

  The package "util" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file and make sure to prefix the module name with "node:" to enable Node.js compatibility.


X [ERROR] Could not resolve "stream"

    node_modules/jws/lib/sign-stream.js:5:21:
      5 │ var Stream = require('stream');
        ╵                      ~~~~~~~~

  The package "stream" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file and make sure to prefix the module name with "node:" to enable Node.js compatibility.
// ......
```
I've been trying for a whole day and couldn't figure it out. Could you please help me? I'm new to this and it's my first attempt. Any assistance would be greatly appreciated.

**Comment by RobertCraigie** [comment]
Hey @winter2399, like the error message suggests, you'll need to add the `node_compat` flag to your config https://developers.cloudflare.com/workers/runtime-apis/nodejs/#enable-nodejs-with-workers.

Sorry our docs don't make this clear, I'll update them.

**Comment by abs612** [comment]
> Hey @winter2399, like the error message suggests, you'll need to add the `node_compat` flag to your config https://developers.cloudflare.com/workers/runtime-apis/nodejs/#enable-nodejs-with-workers.
> 
> Sorry our docs don't make this clear, I'll update them.

The default project configuration comes built-in.
![image](https://github.com/anthropics/anthropic-sdk-typescript/assets/144533817/0bfa3078-390f-453b-9d5b-3d0974a69542)

`node_compat = true` Adding this option didn't work either.
```
X [ERROR] The `nodejs_compat` compatibility flag cannot be used in conjunction with the legacy `--node-compat` flag. If you want to 
use the Workers runtime Node.js compatibility features, please remove the `--node-compat` argument from your CLI command or `node_compat = true` from your config file.
```
https://community.cloudflare.com/t/questions-involving-node-js-compat-issues/547534

**Comment by RobertCraigie** [comment]
ah okay, thanks for the additional details.

It looks like the change cloudflare made to require `node:` prefixes in imports breaks with [`jws`](https://www.npmjs.com/package/jws), a transitive dep of `google-auth-library` which has not had a new release in 5 years...

I'll see what we can do but for now your best bet might be to patch the `stream` import in that dependency using something like [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by abs612** [comment]
> ah okay, thanks for the additional details.
> 
> It looks like the change cloudflare made to require `node:` prefixes in imports breaks with [`jws`](https://www.npmjs.com/package/jws), a transitive dep of `google-auth-library` which has not had a new release in 5 years...
> 
> I'll see what we can do but for now your best bet might be to patch the `stream` import in that dependency using something like [patch-package](https://www.npmjs.com/package/patch-package)

Thank you very much for your reply, and thank you for your hard work.
