### ISSUE TITLE
What is the maximum value of "top_p"

### ISSUE THREAD

**Issue by Pickra** [anthropics/anthropic-sdk-typescript#484]
I'm assuming the max value is 1 but:
- I can't find it in the [docs](https://docs.anthropic.com/en/api/complete) or any of examples
- i got no response in the [discord](https://discord.com/channels/1072196207201501266/1266061198428868698/1266061198428868698)
- I'm waiting on a response from the help bot

Thank you

**Comment by aaron-lerner** [comment]
The maximum value is indeed 1. If you try to send a request with a larger value, you'll get the following error that gives you the range of valid values:
```
{
  "type": "error",
  "error": {
    "type": "invalid_request_error",
    "message": "top_p: range: -1 or 0..1"
  }
}
```
