### ISSUE TITLE
Error: It looks like you're running in a browser-like environment, which is disabled to protect your secret API credentials from attackers. If you have a strong business need for client-side use of this API, please open a GitHub issue with your use-case and security mitigations.

### ISSUE THREAD

**Issue by sheepbox8646** [anthropics/anthropic-sdk-typescript#493]
When I use LangChainJS to require it in browser enviroment, it errors out.

```
Error: It looks like you're running in a browser-like environment, which is disabled to protect your secret API credentials from attackers. If you have a strong business need for client-side use of this API, please open a GitHub issue with your use-case and security mitigations.
```

I am not sure i should open a issue at here, so if i get wrong place, please pardon me.

My project is a animation generator based on [Newcar Animation Engine](https://github.com/dromara/newcar), it is developed by me, now i want to use LLM to make a animation generator based on it. Now the code has been open-sorce. [Repo is Here](https://github.com/Bug-Duck/llmvision) I have try many models but the performance is not great. My friend suggested me to use Claude, so i want to have a try but there is a pity that I have not server so that i only can use netlify and some static page server to deploy the website. Does there have any solution?

**Comment by RobertCraigie** [comment]
Hey @sheepbox8646, see #219 for some prior discussion here. Unfortunately the Anthropic API currently doesn't work from browsers.

**Comment by sheepbox8646** [comment]
Okay, Thanks

**Comment by wong2** [comment]
I'm using the SDK in my browser extension, which does not have CORS restrictions, it used to work fine. But the recent update breaks it suddenly.

I'd suggest change the error to a warning instead of an exception.

**Comment by x5a** [comment]
@sheepbox8646 @wong2 our latest SDK release now offers CORS support [[changelog](https://github.com/anthropics/anthropic-sdk-typescript/blob/main/CHANGELOG.md#0270-2024-08-21)].
