### ISSUE TITLE
Can 'end' event fire if the 'error' event has already fired when streaming?

### ISSUE THREAD

**Issue by GaurangTandon** [anthropics/anthropic-sdk-typescript#501]
Hi! I have a simple Claude Sonnet streaming setup with Anthropic NodeJS SDK with this code:

```js
  /** @type {Anthropic.Messages.MessageStreamParams} */
  const payload = {
    max_tokens,
    system,
    messages,
    model: 'claude-3-5-sonnet-20240620',
    metadata: { user_id, },
  };

  const stream = anthropicClient.messages
    .stream(payload)
    .on('streamEvent', (event, snapshot) => {
      // code D
    })
    .on('text', (text) => {
      // code A
    })
    .on('end', () => {
      // code B
    })
    .on('error', (error) => {
      // code C
    });

  try {
    await stream.finalMessage();
  } catch (e) {
    // we already handled potential errors in the on('error') handler above
  }
```

As per our server logs, it seems code B fires after code C has fired. I checked the SDK code and looks like either 'end' or 'error' can fire but not both, see below:

https://github.com/anthropics/anthropic-sdk-typescript/blob/75c57e10e4545aa873c0d538069fc483e0cacc84/src/lib/MessageStream.ts#L111-114

I want to make sure that is the case: that exactly one of code B or code C will run. Is that true?

Apologies if there's existing documentation on this, would appreciate if you could link me to it. Thanks!

**Comment by RobertCraigie** [comment]
> I want to make sure that is the case: that exactly one of code B or code C will run. Is that true?

no, both will be fired, in the order you observed.

internally when the `error` event is fired, we also fire `end`:
https://github.com/anthropics/anthropic-sdk-typescript/blob/75c57e10e4545aa873c0d538069fc483e0cacc84/src/lib/MessageStream.ts#L340

> Apologies if there's existing documentation on this, would appreciate if you could link me to it. Thanks!

I don't think we have docs that call this particular question out strongly but here's the docs for `.on('end')`: https://github.com/anthropics/anthropic-sdk-typescript/blob/main/helpers.md#onend---

**Comment by GaurangTandon** [comment]
Thanks for your clear and detailed response!
