### ISSUE TITLE
vertex-sdk: Streaming not working with client.messages.stream

### ISSUE THREAD

**Issue by rxliuli** [anthropics/anthropic-sdk-typescript#510]
When I try to use client.messages.stream, it doesn't return a stream of responses. Instead, it only returns the last message.

```ts
const r2 = client.messages.stream({
  model: import.meta.env.VITE_VERTEX_ANTROPIC_MODEL,
  max_tokens: 1000,
  temperature: 0,
  messages: [
    {
      role: 'user',
      content: 'Hello!',
    },
  ],
  stream: true,
})
await new Promise<void>((resolve, reject) => {
  r2.on('message', (it) => {
    console.log('message: ', it)
  })
    .on('error', reject)
    .on('end', resolve)
})
```

<img width="723" alt="image" src="https://github.com/user-attachments/assets/115d0e8a-9e5a-4d3f-9758-316937b272d6">

However, if I use client.messages.create, it works as expected:

```ts
const r2 = client.messages.create({
  model: import.meta.env.VITE_VERTEX_ANTROPIC_MODEL,
  max_tokens: 1000,
  temperature: 0,
  messages: [
    {
      role: 'user',
      content: 'Hello!',
    },
  ],
  stream: true,
})
for await (const it of await r2) {
  console.log(it)
}
```

<img width="575" alt="image" src="https://github.com/user-attachments/assets/4499f08d-46a4-45fa-ad74-e4c65c4553e2">

**Comment by RobertCraigie** [comment]
The `message` event is only fired when the message is complete, if you want the individual stream events you can use `.on('streamEvent')`.

Sorry this wasn't clear, here's our docs: https://github.com/anthropics/anthropic-sdk-typescript/blob/main/helpers.md#onstreamevent-event-messagestreamevent-snapshot-message--
