### ISSUE TITLE
Typescript properties for prompt caching

### ISSUE THREAD

**Issue by adelespinasse** [anthropics/anthropic-sdk-typescript#535]
I see that there are alternate type definitions that support e.g. the `cache_control` property in the "beta" directory, e.g. [here](https://github.com/anthropics/anthropic-sdk-typescript/blob/b7e21131de5cf9d741e3722393285b35eff26c1e/src/resources/beta/prompt-caching/messages.ts#L65). But it's not clear to me how to import and use these definitions instead of the normal ones. Is it possible?

**Comment by RobertCraigie** [comment]
@adelespinasse do you mean accessing the API methods? That looks like this
```ts
const message = await client.beta.promptCaching.messages.create({
  max_tokens: 1024,
  messages: [{ content: 'Hello, world', role: 'user' }],
  model: 'claude-3-5-sonnet-20240620',
});
```
for importing and referencing the types you can do so like this
```ts
import { PromptCachingBetaCacheControlEphemeral } from '@anthropic-ai/sdk/resources/beta/prompt-caching/messages'
```
Does that help?

**Comment by adelespinasse** [comment]
Yes, that's what I was looking for. Using `client.beta.promptCaching` instead of `client` is the most important part; not sure how long it would have taken for me to figure that out on my own.

I was kinda hoping I could just change `import Anthropic from "@anthropic-ai/sdk"` to something else, and not have to change anything else, but this will do for now.

Thank you!
