### ISSUE TITLE
I need a way to calculate and show token counts for each message

### ISSUE THREAD

**Issue by shawhu** [anthropics/anthropic-sdk-typescript#558]
I've tried the old tokenizer, it doesn't work with React Native. Because the old tokenizer depends on tiktoken and although the recent version of RN added support for TextEncoder, it still doesn't have TextDecoder with its default js engine Hermès. And tiktoken uses TextDecoder. I've tried polyfill with @bacons/text-decoder and it also failed with errors like: invalid escape characters... 

so here I am. what are my options? I understand that I can get .usage from the response. but...how do I estimate the message generated by the user before sending to the API?

**Comment by RobertCraigie** [comment]
There is now a new API for getting token counts! https://docs.anthropic.com/en/api/messages-count-tokens
