### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ankitgupta401** [anthropics/anthropic-sdk-typescript#56]
Can you guys please add something that will output the response in a structured format? 
Something like OpenAI Function calling. That feature will help developers get structured responses to build on top of the output received from LLM.

**Comment by rattrayalex** [comment]
Thanks for the idea, we'll be sure to take it into consideration!

**Comment by art-shen** [comment]
Did you consider it? )

Please, it's crucial for so many applications.
