### ISSUE TITLE
Bug: Incorrect Handling of German Quotation Marks in Tool use and Claude App

### ISSUE THREAD

**Issue by koljam** [anthropics/anthropic-sdk-typescript#561]
## Description

There appears to be an issue with the handling of German quotation marks (Unicode U+201E for opening and U+201C for closing) in the Anthropic SDK and potentially in the Claude model itself. Specifically:

1. When prompting Claude to produce a text containing a German closing quotation mark, the response does not correctly preserve this character.
2. In the Claude web application, Claude seems unable to produce German closing quotation marks (Unicode U+201C) at all.

This issue affects the accuracy and usability of the API for languages that use these quotation marks, particularly German.

## Steps to Reproduce

1. Clone the repository: https://github.com/koljam/claude-quotation-mark-bug
2. Install dependencies: `npm install`
3. Set up your Anthropic API key in the `.env` file
4. Run the test script: `node index.js`

## Expected Behavior

The API should correctly preserve and return the German quotation marks as they were in the input.

## Actual Behavior

The API response incorrectly transforms the German quotation marks, returning malformed JSON.

## Environment

- Anthropic SDK version: 0.29.2
- Node.js version: v22.5.1
- Operating System: Windows 11

## Additional Context

This issue is not limited to the SDK. In the Claude web application, Claude seems unable to produce German closing quotation marks (Unicode U+201C) at all, suggesting the problem might be in the underlying model or parsing.

## Impact

This bug prevents the generation of valid JSON when German quotation marks are present, rendering Claude's tool use capabilities unreliable for any application that may encounter such text. As a result, tools expecting valid JSON as input or output fail to function correctly, leading to parsing errors, crashes, or unexpected behavior in applications consuming Claude's responses. This effectively limits the API's practical applications in diverse, multilingual environments and forces developers to implement complex, potentially error-prone workarounds.

---

Thank you for your attention to this issue. Let me know if you need any further information or clarification.

**Comment by koljam** [comment]
I just noticed, that the character `‘` (U+2018) is also effected and "converted" to the English counterpart.

**Comment by koljam** [comment]
For those encountering this issue, you can work around this by converting German quotation marks in your input data before sending it to the API:

```javascript
function convertQuotationMarks(data) {
    if (typeof data === "string") {
        return convertGermanQuotationMarksToEnglish(data);
    } else if (Array.isArray(data)) {
        return data.map(item => convertQuotationMarks(item));
    } else if (typeof data === "object" && data !== null) {
        return Object.fromEntries(
            Object.entries(data).map(([key, value]) => [key, convertQuotationMarks(value)])
        );
    }
    return data;
}

function convertGermanQuotationMarksToEnglish(text) {
    return text
	.replace(/„/g, '"')
	.replace(/“/g, '"')
	.replace(/‚/g, "'")
	.replace(/‘/g, "'");
}
```

Apply this conversion to your input data before sending it to the Anthropic API:

```javascript
const convertedConfig = convertQuotationMarks(yourConfig);
// Use convertedConfig with the API
```

This is a workaround, not a permanent solution. It may not be suitable for all use cases, especially where preserving original quotation marks is crucial.

**Comment by aaron-lerner** [comment]
Hi @koljam, thanks for reporting! Unfortunately, this is not something we're able to fix in the near future. Normalizing quotation marks to the straight ones as you suggest is a reasonable workaround. If you need to ensure the model reads and/or generates smart quotation marks correctly, you can try passing them in a different format such as escaped unicode or https://en.wikipedia.org/wiki/Numeric_character_reference (the latter should be rendered by claude.ai correctly).

**Comment by diesel-zhong** [comment]
> Hi @koljam, thanks for reporting! Unfortunately, this is not something we're able to fix in the near future. Normalizing quotation marks to the straight ones as you suggest is a reasonable workaround. If you need to ensure the model reads and/or generates smart quotation marks correctly, you can try passing them in a different format such as escaped unicode or https://en.wikipedia.org/wiki/Numeric_character_reference (the latter should be rendered by claude.ai correctly).

Escaping in the input even as a temporary solution is very unreliable. It is possible that Claude could add quotes to the result depending on the semantics, and that would also lead to errors in parsing the json
