### ISSUE TITLE
countTokens not working with @anthropic-ai/vertex-sdk

### ISSUE THREAD

**Issue by yarnie046** [anthropics/anthropic-sdk-typescript#593]
Hi, I encountered this issue today. I tried updating to the latest version, but it's still not working.

Here is some information about the library:

Name: @anthropic-ai/vertex-sdk
Version: 0.5.2
I am trying to count the tokens of a message when using AnthropicVertex.

![image](https://github.com/user-attachments/assets/a32ec32b-2182-4f7d-b419-943d07d84913)

However, it returns an error:

![image](https://github.com/user-attachments/assets/9f74ecce-419a-4112-9c48-80e5989cd412)

I checked in the library, and it seems to be calling the endpoint v1/messages/count_tokens?beta=true.

![image](https://github.com/user-attachments/assets/bcca7aec-e3d3-4326-a016-26014a8177a1)

Does anyone have any ideas on how to resolve this issue? Thank you for reading this

**Comment by thuynt46** [comment]
heyyy! anyone see meee

**Comment by RobertCraigie** [comment]
Thanks for the report, this endpoint isn't supported in the vertex API unfortunately. This method will be removed in the next release.
