### ISSUE TITLE
Missing `extra_body` parameter

### ISSUE THREAD

**Issue by jackfischer** [anthropics/anthropic-sdk-typescript#61]
In the Python client, you can use the `extra_body` field to pass in additional content to the request body [[1]](https://github.com/anthropics/anthropic-sdk-python/blob/2a8a202bdae2e49341621ab6d16eadc338ded611/src/anthropic/_base_client.py#L1313), letting you add information for proxies while maintaining type checking. 

However, in the typescript client this appears to be missing, and the user is forced to disable type checking on the relevant line.

```typescript
anthropic.completions.create({
    max_tokens_to_sample: 1000,
    ...
    // @ts-ignore
    thirdPartyField: { } 
})
```

**Comment by rattrayalex** [comment]
Adding a `@ts-ignore` feels germane here; note you could also perform interface merging with the `CompletionCreateParams` type like so:

```ts
declare module '@anthropic-ai/sdk' {
  interface CompletionCreateParams {
    thirdPartyField: MyThirdPartyField
  }
}
```
Would that work for you?

**Comment by jackfischer** [comment]
Thanks, the `declare module` workaround is a great trick.
