### ISSUE TITLE
How to use Anthropic API with OpenAI SDK?

### ISSUE THREAD

**Issue by punkpeye** [anthropics/anthropic-sdk-typescript#620]
I have tried:

```ts
if (llmProviderNid === 'anthropic') {
  return new OpenAI({
    apiKey: config.ANTHROPIC_API_KEY,
    baseURL: 'https://api.anthropic.com/v1',
    dangerouslyAllowBrowser: config.VITEST,
  });
}
```

but I am getting:

```
AuthenticationError: 401 Invalid bearer token
```

The token itself is correct, so I suspect the error is elsewhere.

**Comment by RobertCraigie** [comment]
sorry I'm confused, why are you trying to use the OpenAI SDK with the Anthropic API? this repo is for the Anthropic SDK

**Comment by punkpeye** [comment]
> sorry I'm confused, why are you trying to use the OpenAI SDK with the Anthropic API? this repo is for the Anthropic SDK

Because they are supposed to be compatible APIs.

**Comment by RobertCraigie** [comment]
Where did you see that claim? The APIs are not compatible.

**Comment by punkpeye** [comment]
yikes. looks like it is indeed incompatible. well that sucks
