### ISSUE TITLE
How do I use conversational API of Anthropic?

### ISSUE THREAD

**Issue by siddarth-getethos** [anthropics/anthropic-sdk-typescript#84]
We wanted to make a sequence of request using Anthropic.
In each request we are planning to send big json files.
When are we planning to launch conversational feature of Anthropic so that chat history and context gets saved.

**Comment by rattrayalex** [comment]
For now, you need to keep track of conversational history when making requests to the API. Please follow the Anthropic blog, or watch this repo, to be made aware of any future changes to the API.
